security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: email
        api_service_provider:
            entity:
                class: App\Entity\ServiceProvider
                property: id
        api_provider:
            chain:
                providers: [ "user_provider", "api_service_provider" ]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api/
            stateless: true
            provider: api_provider
            access_token:
                token_handler: App\Security\AccessTokenHandler
        main:
            lazy: true
            provider: user_provider
            custom_authenticator: App\Security\AppUserAuthenticator
            logout:
                path: app_logout
                invalidate_session: false # Will be invalidated in EventSubscriber/LogoutSubscriber.php
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check
                trusted_parameter_name: _trusted

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:
        - { path: ^/logout, role: PUBLIC_ACCESS }
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }

        - { path: ^/oauth/code, roles: ROLE_USER }
        - { path: ^/api, roles: [ ROLE_USER, ROLE_SERVICE ] }
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
