twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        - '%kernel.project_dir%/public/icons'
    globals:
        app_name: '%app.name%'

when@test:
    twig:
        strict_variables: true
